server:
  port: 8206

spring:
  application:
    name: service-user

  redis:
    host: 192.168.10.105
    port: 6379

    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    database: 0
    timeout: 1800000


  datasource:
    url: jdbc:mysql://localhost:3306/yygh_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 980918
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      server-addr: localhost:8848
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl