server:
  port: 8204

spring:
  application:
    name: service-msm
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 192.168.10.105
    port: 6379

    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    database: 0
    timeout: 1800000
  cloud:
    nacos:
      server-addr: localhost:8848
  profiles:
    active: dev

aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI5tDGu6LmhVawXEDxuV2r
    secret: k6HbtlD7tkluhx8EsfvLV0oD2yszeX

