#服务端口
server:
  port: 8201

spring:
  application:
    name: service-hosp

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 980918
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    mongodb:
      uri: mongodb://192.168.10.105:27017/yygh_hosp


##配置mapper.xml文件的路径
#mybatis-plus.mapper-locations=classpath:com.achang.yygh.mapper/xml/*.xml

##nacos服务地址
#spring.cloud.nacos.discovery.server-addr=localhost:8848
#
##开启sentinel
#spring.cloud.sentinel.enabled=true
#
##设置sentinel地址
#spring.cloud.sentinel.transport.dashboard=http://localhost:8858
#
##mongodb地址
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=yygh_hosp
#
##rabbitmq地址
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
